# nome da pipeline
name: "Playwright E2E Tests (Mocha)"

on:
    # Permite que a pipeline seja executada manualmente pela interface do GitHub
    workflow_dispatch:

    # Também pode ser executada quando houver um push na branch main, caso queira testar o processo de CI/CD
    push:
      branches:
        - main  

    schedule:
      - cron: "26 14 * * 5-6" # Executa todos as sextas-feiras às 14:26 UTC (14:10 horário de Brasília)
  
jobs:
    #nome do job
    e2e-tests:
        # maquina onde o job vai rodar
        runs-on: ubuntu-24.04

        env:
          TZ: "America/Sao_Paulo" # Define o timezone para todo o job

        # passos do job
        steps:
          - name: Mostrar data
            run: date

          # clone do projeto (atualizado para v4 estável)
          - uses: actions/checkout@v5

          # instalação do node (ajustado para v22.x LTS estável)
          - uses: actions/setup-node@v5
            with:
              node-version: 22.x
            
          - name: Install NPM Dependencies
            run: npm ci

          - name: Install Browser Binaries
            run: npx playwright install --with-deps
            
          #Instalando o reporter diretamente na pasta local do projeto
          - name: Instalando Mocha JUnit Reporter Localmente
            run: npm install mocha-junit-reporter --save-dev
            
          # Executando testes (agora ele vai encontrar o reporter local)
          - name: Executando testes
            run: npm test

          # Salvando o XML no GitHub para você conseguir baixar depois
          - name: Salvar relatório como artefato
            uses: actions/upload-artifact@v5
            if: always() # Rodar mesmo se algum teste falhar
            with:
              name: resultados-dos-testes
              path: ./test-results.xml

          - name: Publicar Resumo dos Testes na aba Summary
            uses: test-summary/action@v2
            with:
              paths: './test-results.xml' # O caminho exato do arquivo gerado pelo Mocha
            if: always() # GARANTE que o resumo seja publicado mesmo se algum teste falhar
