# nome da pipeline
name: "Execução Manual"

on:
    workflow_dispatch:

jobs:
    #nome do job
    e2e-tests:
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest

        # passos do job
        steps:
            # clone do projeto
            - uses: actions/checkout@v7

            # instalção do node
            - uses: actions/setup-node@v4
              with:
                  node-version: 24.x
            
            - name: Install NPM Dependencies
              run: npm ci

            - name: Install Browser Binaries
              run: npx playwright install --with-deps

            # instalação do Mocha            
            - name: Instalando Mocha
              run: npm install -g mocha 
            
            # Executando testes
            - name: Executando testes
              run: npm test